[package]
name = "api_call"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
error-chain = "0.12.4"
tokio = { version = "0.2.3", features = ["full"] }
serde_json = "1.0.121"
serde = {version = "1.0", features = ["derive"]}
